spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=contafree
spring.datasource.password=contafree123
jwt.secret=r6wu9V0fVmMq6lifX3FzfcIa6tK9MHemFULYX1eK2A3
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800 
logging.level.org.springframework.security=DEBUG