FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
COPY common ./common
RUN mvn -f common/pom.xml install -DskipTests -B

COPY auth-service/pom.xml ./auth-service/pom.xml
RUN mvn -f auth-service/pom.xml dependency:go-offline -B

COPY auth-service/src ./auth-service/src
RUN mvn -f auth-service/pom.xml clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/auth-service/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
