spring.application.name=transactions-service
server.port=8082

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (must match auth-service secret)
jwt.secret=${JWT_SECRET}

# Accounting service (inter-service communication)
accounting.service.url=${ACCOUNTING_SERVICE_URL:http://localhost:8081}

# Swagger / OpenAPI
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.default-models-expand-depth=-1
